### ISSUE TITLE
nil pointer dereference because of unset end block

### ISSUE THREAD

**Issue by fschoell** [streamingfast/substreams-sink-sql#1]
Recent commit fails due to the end block not set properly, see: 

```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x212bfad]

goroutine 102 [running]:
github.com/streamingfast/substreams-sink.(*Sinker).run(0xc000e2b580, {0x28e5020?, 0xc0007e9e00}, 0xc0004d51d0, 0xc0001bd0e0)
        /Users/work/.go/pkg/mod/github.com/streamingfast/substreams-sink@v0.0.0-20230109200258-eb885b8f29df/sinker.go:115 +0x8d
github.com/streamingfast/substreams-sink.(*Sinker).Start(0xc000e2b580, {0x28e5020, 0xc0007e9e00}, 0x28dbe40?, 0xc00084b037?)
        /Users/work/.go/pkg/mod/github.com/streamingfast/substreams-sink@v0.0.0-20230109200258-eb885b8f29df/sinker.go:108 +0x177
github.com/streamingfast/substreams-sink-postgres/sinker.(*PostgresSinker).Run(0xc0006ff320, {0x28e5020, 0xc0007e9e00})
        /Users/work/GoLand/substreams-sink-postgres/sinker/sinker.go:164 +0x472
github.com/streamingfast/substreams-sink-postgres/sinker.(*PostgresSinker).Start(0xc0006ff320, {0x28e5020, 0xc0007e9e00})
        /Users/work/GoLand/substreams-sink-postgres/sinker/sinker.go:116 +0x358
main.sinkRunE.func3()
        /Users/work/GoLand/substreams-sink-postgres/cmd/substreams-sink-postgres/run.go:153 +0x3c
created by main.sinkRunE
        /Users/work/GoLand/substreams-sink-postgres/cmd/substreams-sink-postgres/run.go:152 +0x1265
```

Postgres sink is run without start/stop parameters.

**Comment by maoueh** [comment]
@colindickson

**Comment by colindickson** [comment]
@fschoell A fix has been pushed to the develop branch.   Please re-install `substreams-sink-postgres` with the latest changes
